name: Bug report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you see? What did you expect?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant logs (redact secrets)
      render: shell

  - type: input
    id: version
    attributes:
      label: Version
      description: ask4me / ask4me-server / ask4me-cli / ask4me-sdk versions

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS / arch / runtime details
